# Generated by Django 5.0.2 on 2024-11-23 11:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Worship', 'Worship'), ('Production', 'Production'), ('Real Life', 'Real Life'), ('Campus', 'Campus'), ('Multimedia', 'Multimedia'), ('OPS', 'OPS')], max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('is_youth_minister', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.ImageField(null=True, upload_to='ministers/')),
                ('start_date', models.DateField(null=True)),
                ('disciples', models.IntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minister_profile', to=settings.AUTH_USER_MODEL)),
                ('ministry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ministers', to='ministry.ministry')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.minister')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('duties', models.TextField(default='')),
                ('attended', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_slot', models.CharField(choices=[('7am-9am', '7am-9am'), ('9am-11am', '9am-11am'), ('1pm-3pm', '1pm-3pm')], default='7am-9am', max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministry.minister')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.ministry')),
            ],
        ),
    ]
