# Generated by Django 5.0.2 on 2024-03-23 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.minister')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField()),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.minister')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.ministry')),
            ],
        ),
    ]
