# Generated by Django 5.0.2 on 2024-04-18 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0003_remove_minister_fam_remove_ministry_minister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='minister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ministry.minister'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='ministry.ministry'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
