# Generated by Django 5.0.2 on 2024-04-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0004_alter_schedule_minister_alter_schedule_ministry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='attended',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
