# Generated by Django 5.0.2 on 2024-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0005_schedule_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='minister',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='minister',
            name='disciples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='minister',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='minister',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='ministers/'),
        ),
        migrations.AddField(
            model_name='minister',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
