# Generated by Django 5.0.2 on 2024-05-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0006_minister_address_minister_disciples_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ministry',
            name='ministers',
        ),
        migrations.AddField(
            model_name='minister',
            name='ministry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ministers', to='ministry.ministry'),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='name',
            field=models.CharField(choices=[('Worship', 'Worship'), ('Production', 'Production'), ('Real Life', 'Real Life'), ('Campus', 'Campus'), ('Multimedia', 'Multimedia'), ('OPS', 'OPS')], max_length=50, unique=True),
        ),
    ]
