# Generated by Django 5.0.2 on 2024-05-16 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0007_remove_ministry_ministers_minister_ministry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='notes',
        ),
        migrations.AddField(
            model_name='schedule',
            name='duties',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minister',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.minister'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.ministry'),
        ),
    ]
