# Generated by Django 5.0.7 on 2024-10-23 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0012_alter_schedule_end_time_alter_schedule_start_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='minister',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minister_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
