# Generated by Django 5.0.7 on 2024-10-23 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_member_user'),
        ('ministry', '0013_minister_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='members',
            field=models.ManyToManyField(blank=True, to='attendance.member'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='minister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministry.minister'),
        ),
    ]
