# Generated by Django 5.0.7 on 2024-11-01 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0014_schedule_members_alter_schedule_minister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_slot',
            field=models.CharField(choices=[('7am-9am', '7am-9am'), ('9am-11am', '9am-11am'), ('1pm-3pm', '1pm-3pm')], default='7am-9am', max_length=10),
        ),
    ]
