# Generated by Django 5.0.7 on 2024-11-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0016_schedule_end_time_schedule_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='members',
        ),
    ]
