# Generated by Django 5.0.2 on 2024-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField()),
                ('age', models.IntegerField()),
                ('fb_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
