# Generated by Django 5.0.2 on 2024-03-28 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_service_alter_attendance_date_attendance_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.service'),
        ),
    ]
