# Generated by Django 5.0.2 on 2024-03-29 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.service'),
        ),
    ]
