# Generated by Django 5.0.2 on 2024-03-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_service_name_alter_attendance_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(choices=[(7, '7 AM - General Service'), (9, '9 AM - General Service'), (13, '1 PM - Youth Service'), (1, 'Others - Campus Service')]),
        ),
    ]
