# Generated by Django 5.0.2 on 2024-04-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_member_address_member_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_newcomer',
            field=models.BooleanField(default=False),
        ),
    ]
