# Generated by Django 5.0.2 on 2024-05-28 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
