# Generated by Django 5.0.2 on 2024-06-03 03:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_ministerattendance'),
        ('ministry', '0012_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading_groups', to='ministry.minister')),
            ],
        ),
        migrations.CreateModel(
            name='SmallGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.member')),
                ('minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministry.minister')),
                ('small_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='attendance.smallgroup')),
            ],
            options={
                'unique_together': {('small_group', 'member', 'minister')},
            },
        ),
    ]
