# Generated by Django 5.0.2 on 2024-06-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_smallgroup_smallgroupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smallgroupmembership',
            name='minister',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.ministers'),
        ),
    ]
