# Generated by Django 5.0.2 on 2024-06-03 22:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_alter_smallgroupmembership_minister_delete_ministers'),
        ('ministry', '0012_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallGroupAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('attended', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.member')),
                ('minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministry.minister')),
                ('small_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.smallgroup')),
            ],
        ),
    ]
