# Generated by Django 5.0.2 on 2024-06-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_smallgroupattendance'),
        ('ministry', '0012_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smallgroupattendance',
            name='member',
        ),
        migrations.RemoveField(
            model_name='smallgroupattendance',
            name='minister',
        ),
        migrations.AddField(
            model_name='smallgroupattendance',
            name='members',
            field=models.ManyToManyField(blank=True, to='attendance.member'),
        ),
        migrations.AddField(
            model_name='smallgroupattendance',
            name='ministers',
            field=models.ManyToManyField(blank=True, to='ministry.minister'),
        ),
    ]
